// Generated by CoffeeScript 1.9.3
(function() {
  var Blogger,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Blogger = (function(superClass) {
    extend(Blogger, superClass);

    function Blogger(args) {
      Blogger.__super__.constructor.call(this, "Blogger", args);
    }

    Blogger.prototype.main = function() {
      var me;
      me = this;
      this.tabbar = this.find("tabbar");
      this.containers = [this.find("user-container"), this.find("cv-container"), this.find("blog-container")];
      this.cvlist = this.find("cv-list");
      this.bloglist = this.find("blog-list");
      this.tabbar.set("onlistselect", function(e) {
        var el, i, len, ref;
        ref = me.containers;
        for (i = 0, len = ref.length; i < len; i++) {
          el = ref[i];
          ($(el)).hide();
        }
        return ($(me.containers[e.idx])).show();
      });
      this.tabbar.set("items", [
        {
          iconclass: "fa fa-user-circle",
          selected: true
        }, {
          iconclass: "fa fa-info-circle"
        }, {
          iconclass: "fa fa-book"
        }
      ]);
      return (this.find("bt-user-save")).set("onbtclick", function(e) {
        return me.saveUser();
      });
    };

    Blogger.prototype.saveUser = function() {
      var data, db, i, inputs, len, me, v;
      me = this;
      inputs = this.select("[imput-class='user-input']");
      data = {};
      for (i = 0, len = inputs.length; i < len; i++) {
        v = inputs[i];
        data[v.name] = ($(v)).val();
      }
      if (!data.fullname || data.fullname === "") {
        return this.notify("Full name must be entered");
      }
      db = new this._api.DB("user");
      return db.save(data, function(r) {
        if (r.error) {
          return me.error("Cannot save user data");
        }
        return me.notify("User data updated");
      });
    };

    return Blogger;

  })(this.OS.GUI.BaseApplication);

  Blogger.singleton = true;

  this.OS.register("Blogger", Blogger);

}).call(this);

